### ISSUE TITLE
Transfer to ember-cli org?

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/broccoli-asset-rev#142]
👋 @rickharrison 👋 

What do you think about possibly transferring this repo over into the ember-cli organization? If you are open for it, I've sent you an invite to the [ember-cli-repository-transfers](https://github.com/ember-cli-repository-transfers) organization which you _should_ be able to accept and move this project into. From there I'll transfer it into the ember-cli org.

**Comment by rickharrison** [comment]
Just transferred!

**Comment by rwjblue** [comment]
Thanks @rickharrison!
